apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgc-worker
  namespace: pgc-core
  labels:
    app: pgc-worker
    version: "1.0.4"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pgc-worker
  template:
    metadata:
      labels:
        app: pgc-worker
    spec:
      # kubectl create secret -n pgc-core generic pgc-core --from-literal=AWS_ACCESS_KEY_ID='' --from-literal=AWS_SECRET_ACCESS_KEY=''
      serviceAccountName: allowsecrets-sa
      containers:
      - name: pgc-worker
        image: einstein42/pgc_worker_manager:version-1.0.4
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: pgc-core
---
apiVersion: v1
kind: Service
metadata:
  name: pgc-worker
  namespace: pgc-core
spec:
  ports:
    - port: 80
      targetPort: 3000
  type: NodePort
  selector:
    app: pgc-worker