apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgc-frontend
  namespace: pgc-core
  labels:
    app: pgc-frontend
    version: "1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pgc-frontend
  template:
    metadata:
      labels:
        app: pgc-frontend
    spec:
      # kubectl create secret -n pgc-core generic pgc-core --from-literal=AWS_ACCESS_KEY_ID='' --from-literal=AWS_SECRET_ACCESS_KEY=''
      serviceAccountName: allowsecrets-sa
      containers:
      - name: pgc-frontend
        image: einstein42/pgc_frontend_manager:kube
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: pgc-core
