apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: pgc.nonprod.isy.io
spec:
  additionalPolicies:
    node: |
      [
          {
              "Effect": "Allow",
              "Action": "s3:*",
              "Resource": ["arn:aws:s3:::pgc-nonprod-isy-io-ns-logs/*"]
          },
          {
              "Action": [
                  "logs:*"
              ],
              "Effect": "Allow",
              "Resource": "*"
          }
      ]
    master: |
      [
          {
              "Effect": "Allow",
              "Action": "s3:*",
              "Resource": ["arn:aws:s3:::pgc-nonprod-isy-io-ns-logs/*"]
          },
          {
              "Action": [
                  "logs:*"
              ],
              "Effect": "Allow",
              "Resource": "*"
          }
      ]
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://pgc-nonprod-state-store/pgc.nonprod.isy.io
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: false
    legacy: false
  kubelet:
    anonymousAuth: false
    maxPods: 500
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.12.7
  masterPublicName: api.pgc.nonprod.isy.io
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: us-east-1a
    type: Public
    zone: us-east-1a
  - cidr: 172.20.64.0/19
    name: us-east-1b
    type: Public
    zone: us-east-1b
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: pgc.nonprod.isy.io
  name: master-us-east-1a
spec:
  image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-05-13
  machineType: t3a.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-us-east-1a
  role: Master
  subnets:
  - us-east-1a

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: pgc.nonprod.isy.io
  name: nodes
spec:
  image: kope.io/k8s-1.12-debian-stretch-amd64-hvm-ebs-2019-05-13
  machineType: t3a.large
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  subnets:
  - us-east-1a
