apiVersion: v1
kind: Namespace
metadata:
  name: pgc_system
---
apiVersion: v1
kind: Namespace
metadata:
  name:  nodeservers
---
# A role for reading/listing secrets
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
 namespace: pgc_system
 name: allowsecrets-cr
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"] verbs: ["get", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: allowsecrets-sa
  namespace: pgc_system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allowsecrets-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: allowsecrets-cr
subjects:
- kind: ServiceAccount
  name: allowsecrets-sa
  namespace: pgc_system
