apiVersion: v1
kind: Namespace
metadata:
  name: pgc-core
---
apiVersion: v1
kind: LimitRange
metadata:
  name: pgc-core
  namespace: pgc-core
spec:
  limits:
  - default:
      cpu: 125m
      memory: 96Mi
    defaultRequest:
      cpu: 50m
      memory: 40Mi
    type: Container
---
apiVersion: v1
kind: Namespace
metadata:
  name: nodeservers
---
apiVersion: v1
kind: LimitRange
metadata:
  name: nodeservers
  namespace: nodeservers
spec:
  limits:
  - default:
      cpu: 500m
      memory: 384Mi
    defaultRequest:
      cpu: 20m
      memory: 32Mi
    type: Container
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: allowsecrets-sa
  namespace: pgc-core
---
# A role for reading/listing secrets
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
 namespace: pgc-core
 name: allowsecrets-cr
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allowsecrets-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: allowsecrets-cr
subjects:
- kind: ServiceAccount
  name: allowsecrets-sa
  namespace: pgc-core
---
# dashboard serviceaccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kube-system
- kind: ServiceAccount
  name: allowsecrets-sa
  namespace: pgc-core
