apiVersion: v1
kind: Namespace
metadata:
  name: pgc-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: nodeservers
---
# A role for reading/listing secrets
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
 namespace: pgc-system
 name: allowsecrets-cr
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"] verbs: ["get", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: allowsecrets-sa
  namespace: pgc-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: allowsecrets-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: allowsecrets-cr
subjects:
- kind: ServiceAccount
  name: allowsecrets-sa
  namespace: pgc-system
---
# dashboard serviceaccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kube-system
---
# helm serviceaccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system